name: emajlis
description: A professional networking service.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.5+65

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^2.1.0
  another_flushbar: ^1.10.24
  animated_flip_counter: ^0.1.2
  badges: ^2.0.1
  bubble_tab_indicator: ^0.1.4
  buttons_tabbar: ^1.3.1
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  chips_choice: ^2.0.1
  cloud_firestore: ^2.5.3
  cupertino_icons: ^1.0.0
  date_format: ^2.0.2
  date_time_picker: ^2.0.0
  dio: ^4.0.0
  expandable: ^5.0.1
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.7
  flutter_ringtone_player: ^3.0.0
  flutter_email_sender: ^5.0.2
  flutter_calendar_carousel: ^2.0.1
  flutter_local_notifications: ^8.1.1+1
  flutter_share: ^2.0.0
  flutter_sliding_up_panel: ^2.0.1
  flutter_svg: ^0.22.0
  flutter_tindercard: ^0.2.0
  flutter_toggle_tab: ^1.1.3
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.7
  google_ml_kit: ^0.7.2
  http: ^0.13.3
  image_downloader: ^0.30.0
  image_picker: ^0.8.3+2
  intl: ^0.17.0
  linkedin_login: ^2.0.1
  jitsi_meet: ^4.0.0
  package_info_plus: ^1.3.0
  path_provider: ^2.0.2
  percent_indicator: ^3.0.1
  permission_handler: ^8.1.4+2
  pinput: ^1.2.0
  provider: ^5.0.0
  profanity_filter: ^2.0.0
  share: ^2.0.4
  shared_preferences: ^2.0.6
  scrollable_positioned_list: ^0.1.10
  timelines: ^0.1.0
  toggle_switch: ^1.2.0
  timeago: ^3.2.1
  url_launcher: ^6.0.9
  # sign_in_with_apple: ^3.2.0
  apple_sign_in: ^0.1.0
  countup: ^0.1.3
  swipe_cards: ^1.0.0
  swiping_card_deck: ^0.0.3
  location: ^4.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/graphics/
    - assets/images/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.otf
        - asset: assets/fonts/Aeonik-Light.otf
          weight: 100
        - asset: assets/fonts/Aeonik-Light.otf
          weight: 200
        - asset: assets/fonts/Aeonik-Light.otf
          weight: 300
        - asset: assets/fonts/Aeonik-Regular.otf
          weight: 400
        - asset: assets/fonts/Aeonik-Medium.otf
          weight: 500
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 600
        - asset: assets/fonts/Aeonik-Bold.otf
          weight: 700
        - asset: assets/fonts/Aeonik-RegularItalic.otf
          style: italic
    # - family: Trajan Pro
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
