import 'dart:ui';

const Color appBlack = Color(0xFF242424);
const Color svgTextColor = Color(0xFF7C5B0F);
const Color black = Color(0xFF000000);
const Color appBlackBackground = Color(0xFF1C1C1C);
const Color appwhite = Color(0xFFFFFFFF);
const Color appGrey = Color(0xFF707070);
const Color appGrey2 = Color(0xFF7E7E7E);
const Color appGrey3 = Color(0xFF484848);
const Color appGrey6 = Color(0xFF343434);
const Color appGrey4 = Color(0xFFA1A1A1);
const Color appGrey5 = Color(0xFF848484);
const Color appDarkGrey = Color(0xFF161616);
const Color appLightGrey = Color(0xFFC9C9C9);
const Color appyellowBadge = Color(0xFFDFCB11);
const Color appMustardLight = Color(0xFFFFEDC4);
const Color appMustard = Color(0xFFFFBD2A);
const Color appRed = Color(0xFFFF6363);
const Color appRedShadow = Color(0xFFFDABAB);
const Color appLightRed = Color(0xFFFFEBEE);
const Color appGreen = Color(0xFF12BA1E);
const Color appGreenShadow = Color(0xFF9FF5A5);
const Color appBodyGrey = Color(0xFFEEEEEE);
const Color appgreydate = Color(0xFFBBBBBB);
